project:
  type: website

website:
  title: Nick Boyd's Portfolio
  site-url: https://nickfboyd.com
  description: "This is Nick Boyd's personal portfolio"
  navbar:
    right:
      - text: Projects
        href: projects.qmd
      - icon: github
        href: https://github.com/nickfboyd1
      - icon: linkedin
        href: https://linkedin.com/in/nickfboyd
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

